const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Submit report",
        description: "Submit the monthly financial report",
        date: "2025-04-10",
        category: "Finance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Attend meeting",
        description: "Team sync-up at 11 AM",
        date: "2025-04-11",
        category: "Management",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Code review",
        description: "Review pull requests",
        date: "2025-04-12",
        category: "Development",
        active: true,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Design mockup",
        description: "Create UI design for new feature",
        date: "2025-04-09",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix bugs",
        description: "Resolve issues from QA",
        date: "2025-04-08",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Update documentation",
        description: "Add usage details for API v2",
        date: "2025-04-06",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Deploy app",
        description: "Deploy latest build to staging",
        date: "2025-04-07",
        category: "DevOps",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Customer follow-up",
        description: "Call client to confirm feedback",
        date: "2025-04-11",
        category: "Support",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Backup database",
        description: "Ensure daily backup is completed",
        date: "2025-04-10",
        category: "IT",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Fix login issue",
        description: "Investigate login failure for users",
        date: "2025-04-08",
        category: "Development",
        active: true,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Optimize queries",
        description: "Improve performance of slow DB queries",
        date: "2025-04-06",
        category: "Database",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Create test cases",
        description: "Write tests for user module",
        date: "2025-04-05",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Write blog post",
        description: "Post about latest product updates",
        date: "2025-04-09",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Plan webinar",
        description: "Schedule webinar for April 20",
        date: "2025-04-08",
        category: "Marketing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Record tutorial",
        description: "Create a demo video for onboarding",
        date: "2025-04-07",
        category: "Training",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Security audit",
        description: "Check app for vulnerabilities",
        date: "2025-04-10",
        category: "Security",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Prepare slides",
        description: "Create presentation for project review",
        date: "2025-04-11",
        category: "Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Analyze feedback",
        description: "Go through recent survey responses",
        date: "2025-04-09",
        category: "Research",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Refactor codebase",
        description: "Clean up unused components",
        date: "2025-04-06",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Client meeting",
        description: "Discuss Q2 goals with client",
        date: "2025-04-05",
        category: "Sales",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
